# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    
    config.vm.box = "hashicorp/bionic64"
  
    config.trigger.before :up do |t|
      t.info = "Brining up your guest machine"
      t.run = {inline: "bash -c 'echo \"Hey there!!\" > file.txt'"}
    end
      
  
  end
  